// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace aApprosDbContext.Migrations
{
    [DbContext(typeof(ERPCmdtApi.ApprosDbContext.ApprosDbContext))]
    partial class ApprosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aApprosModels.ModelsAppros.AppelOffre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampagneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAttribution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoAppelOffre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoAttribMarche")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<string>("Objet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceDC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.ToTable("AppelOffres");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Cdtnt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Cdtnts");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Contrat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppelOffreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateContrat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFirstLivraison")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastLivraison")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLettreNotification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FournisseurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsAnnule")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsContratAnnexe")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NoAvenant")
                        .HasColumnType("int");

                    b.Property<string>("NoCommande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoContrat")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<int?>("NoLettreNotification")
                        .HasColumnType("int");

                    b.Property<string>("Origine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppelOffreId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("StatusId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.ContratDt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AffectationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContratIntrantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PrixUnitaire")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProduitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Qte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QteResilie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AffectationId");

                    b.HasIndex("ContratIntrantId");

                    b.HasIndex("ProduitId");

                    b.ToTable("ContratDts");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Reception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContratDtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTransComptabilite")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NoBordereau")
                        .HasColumnType("int");

                    b.Property<string>("NoFactureFour")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("NoPiece")
                        .HasColumnType("int");

                    b.Property<string>("NoReception")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContratDtId");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.ReceptionDt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PrixUnitaire")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<int?>("QteDeclare")
                        .HasColumnType("int");

                    b.Property<int?>("QteRe")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid?>("ReceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.ToTable("ReceptionDts");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.UniteAchat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("UniteAchats");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Affectation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Campagne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Debut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Campagnes");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Direction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Fournisseur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RCCM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RepresentantNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentantTitre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Telephone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrege")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Capacite")
                        .HasMaxLength(256)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CdtntId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LibCommercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UniteAchatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CdtntId");

                    b.HasIndex("UniteAchatId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.AppelOffre", b =>
                {
                    b.HasOne("aApprosModels.ModelsBase.Campagne", "Campagne")
                        .WithMany("AppelOffres")
                        .HasForeignKey("CampagneId");

                    b.Navigation("Campagne");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Contrat", b =>
                {
                    b.HasOne("aApprosModels.ModelsAppros.AppelOffre", "AppelOffre")
                        .WithMany("Contrat")
                        .HasForeignKey("AppelOffreId");

                    b.HasOne("aApprosModels.ModelsBase.Fournisseur", "Fournisseur")
                        .WithMany("ContratIntrants")
                        .HasForeignKey("FournisseurId");

                    b.HasOne("aApprosModels.ModelsAppros.Status", "Status")
                        .WithMany("Contrat")
                        .HasForeignKey("StatusId");

                    b.Navigation("AppelOffre");

                    b.Navigation("Fournisseur");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.ContratDt", b =>
                {
                    b.HasOne("aApprosModels.ModelsBase.Affectation", "Affectation")
                        .WithMany("ContratDts")
                        .HasForeignKey("AffectationId");

                    b.HasOne("aApprosModels.ModelsAppros.Contrat", "ContratIntrant")
                        .WithMany("ContratIntrantDts")
                        .HasForeignKey("ContratIntrantId");

                    b.HasOne("aApprosModels.ModelsBase.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.Navigation("Affectation");

                    b.Navigation("ContratIntrant");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Reception", b =>
                {
                    b.HasOne("aApprosModels.ModelsAppros.ContratDt", "ContratDt")
                        .WithMany("Receptions")
                        .HasForeignKey("ContratDtId");

                    b.Navigation("ContratDt");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.ReceptionDt", b =>
                {
                    b.HasOne("aApprosModels.ModelsAppros.Reception", "Reception")
                        .WithMany("ReceptionDt")
                        .HasForeignKey("ReceptionId");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Affectation", b =>
                {
                    b.HasOne("aApprosModels.ModelsBase.Direction", "Direction")
                        .WithMany("Affectations")
                        .HasForeignKey("DirectionId");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Produit", b =>
                {
                    b.HasOne("aApprosModels.ModelsAppros.Cdtnt", "Cdtnt")
                        .WithMany("Produits")
                        .HasForeignKey("CdtntId");

                    b.HasOne("aApprosModels.ModelsAppros.UniteAchat", "UniteAchat")
                        .WithMany("Produits")
                        .HasForeignKey("UniteAchatId");

                    b.Navigation("Cdtnt");

                    b.Navigation("UniteAchat");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.AppelOffre", b =>
                {
                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Cdtnt", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Contrat", b =>
                {
                    b.Navigation("ContratIntrantDts");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.ContratDt", b =>
                {
                    b.Navigation("Receptions");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Reception", b =>
                {
                    b.Navigation("ReceptionDt");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.Status", b =>
                {
                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("aApprosModels.ModelsAppros.UniteAchat", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Affectation", b =>
                {
                    b.Navigation("ContratDts");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Campagne", b =>
                {
                    b.Navigation("AppelOffres");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Direction", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("aApprosModels.ModelsBase.Fournisseur", b =>
                {
                    b.Navigation("ContratIntrants");
                });
#pragma warning restore 612, 618
        }
    }
}
